
//登录
export const LOGIN_IN_DOING = 'LOGIN_IN_DOING';
export const LOGIN_IN_DONE = 'LOGIN_IN_DONE';
export const LOGIN_IN_ERROR = 'LOGIN_IN_ERROR';

export const WAITING_ORDER_IN_DOING = 'WAITING_ORDER_IN_DOING';
export const WAITING_ORDER_IN_DONE = 'WAITING_ORDER_IN_DONE';
export const WAITING_ORDER_IN_ERROR = 'WAITING_ORDER_IN_ERROR';

export const ACCEPT_ORDER_IN_DOING = 'ACCEPT_ORDER_IN_DOING';
export const ACCEPT_ORDER_IN_DONE  = 'ACCEPT_ORDER_IN_DONE';
export const ACCEPT_ORDER_IN_ERROR = 'ACCEPT_ORDER_IN_ERROR';
